site_name: GPTarot - API Documentation
site_description: API Documentation for GPTarot FastAPI Project
docs_dir: docs
repo_url: https://github.com/gptarot/gptarot.api/

nav:
  - Home: index.md
  - Predict API: predict.md
  - Tarot Cards API: tarot-cards.md

theme:
  name: material
  logo: assets/icon.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: "Roboto"
    code: "IBM Plex Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - api
          options:
            # https://mkdocstrings.github.io/python/usage/configuration/general/
            show_bases: false
            show_source: true
            line_length: 120
            find_stubs_package: true
            show_inheritance_diagram: true
            inheritance_diagram_direction: LR

            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true

            # https://mkdocstrings.github.io/python/usage/configuration/headings/
            heading_level: 3
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

            # https://mkdocstrings.github.io/python/usage/configuration/members/
            group_by_category: true

            # https://mkdocstrings.github.io/python/usage/configuration/signatures/
            separate_signature: true
            show_signature_annotations: true
            show_signature: true
            signature_crossrefs: true
            extensions:
              - griffe_pydantic:
                  schema: true
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
  - autorefs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
