version: "3.9"

services:
  gptarot-flask-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gptarot-flask-web
    ports:
      - "5000:5000"
    environment:
      - .env
    volumes:
      - .:/app
    expose:
      - "5000"