version: "3.9"

services:
  gptarot-flask-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gptarot-flask-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT"]
      interval: 30s
      timeout: 10s
      retries: 3