version: "3.9"

services:
  gptarot-flask-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gptarot-flask-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-5000} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3