name: deploy-docs
on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv sync --all-groups --all-extras
      - run: uv run mkdocs build --clean --site-dir site
      - name: Deploy docs to tarotpedia/docs
        run: |
          git clone "https://${{ secrets.DOCS_DEPLOY_USER }}:${{ secrets.DOCS_DEPLOY_TOKEN }}@github.com/tarotpedia/docs.git" --depth 1 /tmp/deploy-docs
          find /tmp/deploy-docs -mindepth 1 -maxdepth 1 -not -name 'README.md' -not -name '.git' -exec rm -rf '{}' +
          cp -rf site/* /tmp/deploy-docs/
          cd /tmp/deploy-docs
          git add --all
          git commit -m "docs: update api docs by commit ${{ github.sha }}"
          git push origin main
