on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  uv-pre-commit:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install node for prettier in pre-commit
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Set up dependencies
        run: uv sync --all-groups --all-extras

      - name: Run uv pre-commit to test
        run: uv pre-commit run --all-files

      - name: Minimize uv cache
        run: uv cache prune --ci
